export const siteConfig = {
  name: "Reyhaneh Tavakolipour",
  title: "Senior Android and KMP Developer",
  description: "Portfolio website of Reyhaneh Tavakolipour",
  accentColor: "#ea580c",
  social: {
    email: "reyhanehtavakolipour@gmail.com",
    linkedin: "https://www.linkedin.com/in/reyhaneh-tavakolipour/",
    github: "https://github.com/reyhanehtavakolipour",
  },
  aboutMe:
    "I'm a Senior Mobile Developer with 9+ years of experience building Android and cross-platform applications. I'm passionate about system design, clean architecture, and creating software that is scalable, maintainable, and easy to evolve. Over the years, I've worked on both startup and enterprise products, taking ownership of architecture, development, and long-term product growth. More recently, I've focused on Kotlin Multiplatform, building cross-platform applications from the ground up while maintaining production Android and iOS apps. I enjoy solving complex technical challenges and turning ideas into reliable, user-focused products.",
  skills: [
    "Designs scalable Android architectures with clear separation between domain, data, and presentation layers.",
    "Strong focus on offline-first and single source of truth patterns in production apps.",
    "Experienced in evolving legacy Android codebases into modular, testable systems.",
    "Owns features end-to-end from design discussions to production rollout.",
    "Builds resilient apps with offline support, caching strategies, and graceful API failure handling.",
    "Strong experience with production debugging and crash reduction.",
    "Works closely with designers, backend engineers, and product managers in agile teams.",
    "Leads full-cycle development of Kotlin Multiplatform applications from technical system design and architecture decisions to implementation and production deployment across Android and iOS.",
    "CI/CD pipeline ownership for automated Android builds, testing, and production deployments with a focus on reliability and release efficiency.",
  ],
  projects: [
    {
      name: "News App",
      description:
        "Offline-first Android news application built around clean architecture, single source of truth, and custom pagination. The app prioritizes fast perceived performance by showing cached content immediately, refreshing remote data in the background, preserving feed and scroll stability, and handling API failures, duplicates, cache eviction, bookmarks, and battery-aware prefetching with carefully scoped loading and error states.",
      link: "https://github.com/reyhanehtavakolipour/CleanNewsApp",
      skills: [
        "Kotlin",
        "Jetpack Compose",
        "Clean Architecture",
        "Room",
        "Ktor",
        "Koin",
        "Offline-first",
        "Custom Pagination",
      ],
    },
    {
      name: "MasterPie",
      description:
        "Flutter macro-planning and food portion calculator that helps users build meal plans around target calories, protein, carbohydrates, and fat. The app uses a feature-first clean architecture with BLoC, use cases, repository contracts, encrypted local storage, Supabase-backed user data, FatSecret nutrition APIs, AI-assisted meal suggestions, subscription flows, Firebase Crashlytics, and a full food workflow covering search, recipes, favorites, cookbook management, logging, and profile-based macro goals.",
      link: "https://github.com/reyhanehtavakolipour/masterpie",
      skills: [
        "Flutter",
        "Dart",
        "BLoC",
        "Clean Architecture",
        "Supabase",
        "Firebase",
        "Encrypted SQLite",
        "FatSecret API",
        "OpenAI API",
      ],
    },
    {
      name: "Cobalt",
      description: [
        "Solo end-to-end Kotlin Multiplatform implementation of an enterprise incident response and security operations app for Android and iOS. The project combines shared Compose UI, domain, and data layers for authentication, incident templates, task response flows, notification dispatch and status tracking, document sync, Twilio-backed team chat, patrol management, live maps, location updates, NFC checkpoints, and push-driven realtime updates.",
        "The architecture uses feature-first clean modules, optimistic state handling, prefetching for smoother user experience, Koin dependency injection, Ktor safe-call and session refresh infrastructure, Room KMP caching with migrations, background sync, WebSocket reconnection, and native Android/Swift bridges where platform APIs require it.",
        "I structured Crashlytics and analytics-style observability as part of the app architecture: when something fails, non-fatal errors are reported with useful diagnostic context such as user id, organization, route trail, failing function/domain/code, endpoint or payload metadata, and feature-specific keys. This makes production issues faster to reproduce, triage, and trace back to the root cause instead of relying on generic crash reports.",
      ],
      skills: [
        "Kotlin Multiplatform",
        "Compose Multiplatform",
        "Clean Architecture",
        "Ktor",
        "Room KMP",
        "Koin",
        "WebSockets",
        "Firebase",
        "Analytics",
        "MapLibre",
      ],
    },
  ],
  experience: [],
  education: [],
};
